@host=http://localhost:7009

### get ttt
GET {{host}}/ttt/333?name=hong

### users - post
POST {{host}}/users
Content-Type: application/json

{
  "email": "example@example.com",
  "name": "testName"
}